apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - image: my-app:1.0
      name: my-app
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
