apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app-replicaset
spec:
  replicas: 3 # Количество реплик
  selector:
    matchLabels:
      app: my-app # Селектор поиска(отображения) объектов Pod для ReplicaSet
  template:
    metadata:
      labels:
        app: my-app # Метка Pod по которой ReplicaSet будет его искать
    spec:
      containers:
        - name: my-app
          image: my-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - name: http
      port: 80 # Внутренний порт сервиса
      targetPort: 8080 # Порт контейнера
      nodePort: 30080 # Внешний порт узла (для доступа снаружи)
  type: NodePort


#apiVersion: v1
#kind: Pod
#metadata:
#  name: my-app
#spec:
#  containers:
#    - image: my-app:1.0
#      name: my-app
#      imagePullPolicy: IfNotPresent
#      livenessProbe:
#        httpGet:
#          path: /management/health/liveness
#          port: 8080
#        initialDelaySeconds: 15
#        timeoutSeconds: 2
#        periodSeconds: 20
#        failureThreshold: 3
#      readinessProbe:
#        httpGet:
#          path: /management/health/readiness
#          port: 8080
#        initialDelaySeconds: 5
#        timeoutSeconds: 1
#        periodSeconds: 5
#        failureThreshold: 3
#        successThreshold: 1
#      ports:
#        - containerPort: 8080
#          name: http
#          protocol: TCP
